# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=30, verbose_name='域名')),
                ('url', models.CharField(max_length=256, verbose_name='网址')),
                ('uuid', models.CharField(db_index=True, max_length=20, verbose_name='uuid')),
                ('header', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
        ),
    ]
